/*******************************************************************************
 *                       RoadDB Confidential
 *                  Copyright (c) RoadDB 2019-2020
 *
 *      This software is furnished under license and may be used or
 *      copied only in accordance with the terms of such license.
 *******************************************************************************
 * @file   SRDef.h
 * @brief  SRDef 
 *******************************************************************************
 */
#pragma once

namespace RDBVehicleAPI
{
enum SR_TYPE_E
{
    SR_TYPE_SIGN_CLASS_UNKNOWN_E                                       = 0,   /*!< unknown class */
    SR_TYPE_SIGN_CLASS_CLUSTER_GARBAGE_E                               = 999990,   /*!< if cluster garb -> then class id is -1 (legacy from SRCLgetClassId()) */
    SR_TYPE_SIGN_CLASS_SUPPL_RESTRICTED_E                              = 100000,   /*!< pseudo-sign for detection only/uncertain recognition, meaning that a general "restricted" should be displayed */
    SR_TYPE_SIGN_CLASS_SUPPL_ARROW_LEFT_E                              = 100010,   /*!< left arrow, sign is valid for left exit */
    SR_TYPE_SIGN_CLASS_SUPPL_CURVED_ARROW_LEFT_E                       = 100011,   /*!< curved left arrow, sign is valid for left exit */
    SR_TYPE_SIGN_CLASS_SUPPL_ARROW_RIGHT_E                             = 100020,   /*!< right arrow, sign is valid for right exit */
    SR_TYPE_SIGN_CLASS_SUPPL_CURVED_ARROW_RIGHT_E                      = 100021,   /*!< curved right arrow, sign is valid for right exit */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_FOR_DISTANCE_E                      = 100100,   /*!< main sign valid for X meters/kilometers */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_FOR_DISTANCE_METERS_E               = 100130,   /*!< main sign valid for X meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_FOR_DISTANCE_KILOMETERS_E           = 100131,   /*!< main sign valid for X kilometers */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE_E                       = 100400,   /*!< main sign is pre-warning, not valid until in X meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_100_METERS_E                     = 100430,   /*!< main sign is pre-warning, not valid until in 100 meters */
    SR_TYPE_SIGN_CLASS_SUPPL_STOP_IN_100_METERS_E                      = 100431,   /*!< main sign is pre-warning for stop sign in 100 meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_200_METERS_E                     = 100432,   /*!< main sign is pre-warning, not valid until in 200 meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_400_METERS_E                     = 100433,   /*!< main sign is pre-warning, not valid until in 400 meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_600_METERS_E                     = 100434,   /*!< main sign is pre-warning, not valid until in 600 meters */
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_2_KILOMETERS_E                   = 100435,   /*!< main sign is pre-warning, not valid until in 2 kilometers */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_PICT_E                   = 100600,   /*!< main sign with pictogram has purely informational character, no implication on validity */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_TEXT_ONE_ROW_E           = 100601,   /*!< main sign with text has purely informational character, no implication on validity */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_TEXT_TWO_ROWS_E          = 100602,   /*!< main sign with text has purely informational character, no implication on validity */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_TEXT_THREE_ROWS_E        = 100603,   /*!< main sign with text has purely informational character, no implication on validity */
    SR_TYPE_SIGN_CLASS_SUPPL_ZONE_E                                    = 100604,   /*!< main sign with Zone */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_RADAR_E                  = 100628,   /*!< main sign is enforced by radar */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_NOISE_E                  = 100629,   /*!< main sign is posted in order to reduce traffic noise */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_OIL_E                    = 100630,   /*!< main sign is posted because of oil on the road  */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_SMOKE_E                  = 100631,   /*!< main sign is posted because of smoke reducing visibility */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_GRAVEL_E                 = 100632,   /*!< main sign is posted because of loose gravel on the road */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_ROAD_WORKS_EXIT_E        = 100633,   /*!< main sign is posted because of construction trucks entering the road here */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_ROAD_DAMAGE_E            = 100634,   /*!< main sign is posted because of damages to the road */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_DIRT_E                   = 100635,   /*!< main sign is posted because of dirt on the road */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_COLLISION_E              = 100636,   /*!< main sign is posted because danger of collisions */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_FROGS_E                  = 100637,   /*!< main sign is posted because of frogs on the road */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_QUEUE_E                  = 100638,   /*!< main sign is posted because of danger of queues */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_TREES_E                  = 100639,   /*!< main sign is posted because of danger of (trucks) colliding with trees */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_REPETITION_E             = 100650,   /*!< main sign is re-posted here (rappel etc.) */
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_ICE_E                    = 100730,   /*!< main sign is posted because of danger of icy road */
    SR_TYPE_SIGN_CLASS_SUPPL_TIME_RESTRICTION_E                        = 104030,   /*!< main sign has time restriction */
    SR_TYPE_SIGN_CLASS_SUPPL_NIGHT_E                                   = 104040,   /*!< main sign is valid at night */
    SR_TYPE_SIGN_CLASS_SUPPL_WORKDAYS_E                                = 104230,   /*!< main sign is valid on workdays (Mon - Sat) */
    SR_TYPE_SIGN_CLASS_SUPPL_WORKDAYS_AND_TIME_E                       = 104231,   /*!< main sign is valid on workdays (Mon - Sat) and in certain time interval */
    SR_TYPE_SIGN_CLASS_SUPPL_MON2FRI_AND_TIME_E                        = 104233,   /*!< main sign is valid Mon - Fri and in certain time interval */
    SR_TYPE_SIGN_CLASS_SUPPL_MOTORCYCLE_E                              = 104610,   /*!< main sign is valid for two-wheelers */
    SR_TYPE_SIGN_CLASS_SUPPL_MOPED_E                                   = 104611,   /*!< main sign is valid for mopeds */
    SR_TYPE_SIGN_CLASS_SUPPL_MOTORCYCLE_ONLY_E                         = 104612,   /*!< ain sign is valid for motorcycles */
    SR_TYPE_SIGN_CLASS_SUPPL_PASSENGER_CAR_E                           = 104810,   /*!< main sign is valid for passenger cars */
    SR_TYPE_SIGN_CLASS_SUPPL_PASSENGER_CAR_TRAILER_E                   = 104811,   /*!< main sign is valid for passenger cars with trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_BUS_E                               = 104812,   /*!< main sign is valid for trucks and busses */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_TRAILER_E                           = 104813,   /*!< main sign is valid for trucks with a trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_SEMITRAILER_E                       = 104814,   /*!< main sign is valid for trucks with a semi-trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_TRAILER_SEMITRAILER_E               = 104815,   /*!< main sign is valid for trucks with a trailer or semi-trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_BUS_E                                     = 104816,   /*!< main sign is valid for buses */
    SR_TYPE_SIGN_CLASS_SUPPL_MOBILE_HOME_E                             = 104817,   /*!< main sign is valid for mobile homes */
    SR_TYPE_SIGN_CLASS_SUPPL_TRAIN_E                                   = 104818,   /*!< main sign is valid for trains */
    SR_TYPE_SIGN_CLASS_SUPPL_TRAM_E                                    = 104819,   /*!< main sign is valid for trams */
    SR_TYPE_SIGN_CLASS_SUPPL_TRACTOR_E                                 = 104910,   /*!< main sign is valid for tractors */
    SR_TYPE_SIGN_CLASS_SUPPL_TRACTORS_MAY_BE_PASSED_E                  = 104911,   /*!< main sign (no passing) might be ignored when passing tractors */
    SR_TYPE_SIGN_CLASS_SUPPL_TANK_E                                    = 104912,   /*!< main sign is valid for military tanks */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_BUS_CAR_TRAILER_E                   = 104913,   /*!< main sign is valid for trucks, busses and cars with trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_TRUCK_CAR_TRAILER_E                       = 104916,   /*!< main sign is valid for trucks, busses and cars with trailer */
    SR_TYPE_SIGN_CLASS_SUPPL_DANGEROUS_GOODS_E                         = 105230,   /*!< main sign is valid for trucks with dangerous goods */
    SR_TYPE_SIGN_CLASS_SUPPL_DANGEROUS_LIQIUDS_E                       = 105231,   /*!< main sign is valid for tank vehicles with dangerous liquids */
    SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT_E                                  = 105235,   /*!< main sign is valid for vehilce above a certain weight */
    SR_TYPE_SIGN_CLASS_SUPPL_WET_E                                     = 105236,   /*!< main sign is valid when road is wet */
    SR_TYPE_SIGN_CLASS_SUPPL_FOGGY_E                                   = 105237,   /*!< main sign is valid when weather foggy */
    SR_TYPE_SIGN_CLASS_SUPPL_ICY_E                                     = 105238,   /*!< main sign is valid when road is icy */
    SR_TYPE_SIGN_CLASS_SUPPL_SCHOOL_E                                  = 105239,   /*!< main sign is valid when road nearby school */
    SR_TYPE_SIGN_CLASS_SUPPL_X_WAY_E                                   = 105240,   /*!< suppl sign X-Way under stop signs in US */
    SR_TYPE_SIGN_CLASS_SUPPL_SNOW_RAIN_E                               = 105241,
    SR_TYPE_SIGN_CLASS_SUPPL_RAIN_E                                    = 105242,
    SR_TYPE_SIGN_CLASS_SUPPL_ONLY_INFORMATION_GRIT_E                   = 106030,   /*!< sign is indicating container with grit  */
    SR_TYPE_SIGN_CLASS_SUPPL_GARBAGE_E                                 = 100990,   /*!< suppl sign is garbage/not recognized */
    SR_TYPE_SIGN_CLASS_SUPPL_IRRELEVANT_E                              = 100991,   /*!< suppl sign was recognized but marked as not relevant */
    SR_TYPE_SIGN_CLASS_SUPPL_NOT_SUPPORTED_E                           = 100992,   /*!< suppl sign was recognized but is not yet supported */
    SR_TYPE_SIGN_CLASS_DANGER_EXCLAMATION_MARK_E                       = 101000,   /*!< danger sign exclamation mark */
    SR_TYPE_SIGN_CLASS_DANGER_CROSS_ROAD_E                             = 102000,   /*!< danger sign cross road */
    SR_TYPE_SIGN_CLASS_DANGER_BEND_LEFT_E                              = 103010,   /*!< danger sign bend left */
    SR_TYPE_SIGN_CLASS_DANGER_BEND_RIGHT_E                             = 103020,   /*!< danger sign bend right */
    SR_TYPE_SIGN_CLASS_DANGER_DOUBLE_BEND_LEFT_E                       = 105010,   /*!< danger sign double bend left */
    SR_TYPE_SIGN_CLASS_DANGER_DOUBLE_BEND_RIGHT_E                      = 105020,   /*!< danger sign double bend right */
    SR_TYPE_SIGN_CLASS_DANGER_STEEP_HILL_DOWNWARDS_E                   = 108000,   /*!< danger sign hill downwards */
    SR_TYPE_SIGN_CLASS_DANGER_STEEP_HILL_UPWARDS_E                     = 110000,   /*!< danger sign hill upwards */
    SR_TYPE_SIGN_CLASS_DANGER_BUMPS_E                                  = 112000,   /*!< danger sign bumps */
    SR_TYPE_SIGN_CLASS_DANGER_SNOW_E                                   = 113000,   /*!< danger sign snow */
    SR_TYPE_SIGN_CLASS_DANGER_SLIPPERY_ROAD_E                          = 114000,   /*!< danger sign slippery road */
    SR_TYPE_SIGN_CLASS_DANGER_FALLING_ROCKS_E                          = 115000,   /*!< danger falling rocks */
    SR_TYPE_SIGN_CLASS_DANGER_GRAVEL_E                                 = 116000,   /*!< danger sign gravel */
    SR_TYPE_SIGN_CLASS_DANGER_WIND_E                                   = 117000,   /*!< danger sign wind */
    SR_TYPE_SIGN_CLASS_DANGER_ROAD_NARROW_BOTH_SIDES_E                 = 120000,   /*!< danger sign road narrow both sides */
    SR_TYPE_SIGN_CLASS_DANGER_ROAD_NARROW_RIGHT_SIDE_E                 = 121010,   /*!< danger sign road narrow right side */
    SR_TYPE_SIGN_CLASS_DANGER_ROAD_NARROW_LEFT_SIDE_E                  = 121020,   /*!< danger sign road narrow left side */
    SR_TYPE_SIGN_CLASS_DANGER_ROAD_WORK_E                              = 123000,   /*!< danger sign road works */
    SR_TYPE_SIGN_CLASS_DANGER_TRAFFIC_JAM_E                            = 124000,   /*!< danger sign traffic jam*/
    SR_TYPE_SIGN_CLASS_DANGER_TWO_WAY_TRAFFIC_E                        = 125000,   /*!< danger sign two way traffic */
    SR_TYPE_SIGN_CLASS_DANGER_TRAFFIC_LIGHTS_E                         = 131000,   /*!< danger sign traffic lights */
    SR_TYPE_SIGN_CLASS_DANGER_PEDESTRIAN_E                             = 133000,   /*!< danger sign pedestrian */
    SR_TYPE_SIGN_CLASS_DANGER_PEDESTRIAN_ZEBRA_CROSSING_E              = 134000,   /*!< danger sign pedestrian zebra crossing */
    SR_TYPE_SIGN_CLASS_DANGER_DANGER_CHILDREN_E                        = 136000,   /*!< danger sign children */
    SR_TYPE_SIGN_CLASS_DANGER_CYCLIST_CROSSING_E                       = 138000,   /*!< danger sign cyclist crossing */
    SR_TYPE_SIGN_CLASS_DANGER_CATTLE_CROSSING_E                        = 140000,   /*!< danger sign animals crossing */
    SR_TYPE_SIGN_CLASS_DANGER_ANIMAL_CROSSING_E                        = 142000,   /*!< danger sign cattle crossing */
    SR_TYPE_SIGN_CLASS_DANGER_AIR_TRAFFIC_E                            = 144000,   /*!< danger sign air traffic */
    SR_TYPE_SIGN_CLASS_DANGER_BUS_E                                    = 145000,   /*!< danger sign bus */
    SR_TYPE_SIGN_CLASS_DANGER_TRAIN_CROSS_E                            = 151000,   /*!< danger sign train crossing */
    SR_TYPE_SIGN_CLASS_DANGER_GARBAGE_E                                = 109990,   /*!< danger sign not recognized */
    SR_TYPE_SIGN_CLASS_GIVE_WAY_E                                      = 205000,   /*!< sign give way */
    SR_TYPE_SIGN_CLASS_MAIN_LIMIT_E                                    = 274000,   /*!< passive super class */
    SR_TYPE_SIGN_CLASS_MAIN_LIMIT_ACTIVE_E                             = 274001,   /*!< active super class */
    SR_TYPE_SIGN_CLASS_MAIN_SL_005_E                                   = 274505,   /*!< speed limit sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_005_ACTIVE_E                            = 274506,   /*!< active speed limit sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_005_END_E                               = 278505,   /*!< speed limit end sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_005_END_ACTIVE_E                        = 278506,   /*!< active speed limit end sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_010_E                                   = 274510,   /*!< speed limit sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_010_ACTIVE_E                            = 274511,   /*!< active speed limit sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_010_END_E                               = 278510,   /*!< speed limit end sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_010_END_ACTIVE_E                        = 278511,   /*!< active speed limit end sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_015_E                                  = 274515,   /*!< speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_015_ACTIVE_E                            = 274516,   /*!< active speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_015_END_E                               = 278515,   /*!< speed limit end sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_015_END_ACTIVE_E                        = 278516,   /*!< active speed limit end sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_020_E                                  = 274520,   /*!< speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_020_ACTIVE_E                            = 274521,   /*!< active speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_020_END_E                               = 278520,   /*!< speed limit end sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_020_END_ACTIVE_E                        = 278521,   /*!< active speed limit end sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_025_E                                     = 274525,   /*!< speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_025_ACTIVE_E                            = 274526,   /*!< active speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_025_END_E                               = 278525,   /*!< speed limit end sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_025_END_ACTIVE_E                        = 278526,   /*!< active speed limit end sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_030_E                                     = 274530,   /*!< speed limit sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_030_ACTIVE_E                            = 274531,   /*!< active speed limit sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_030_END_E                               = 278530,   /*!< speed limit end sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_030_END_ACTIVE_E                        = 278531,   /*!< active speed limit end sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_035_E                                     = 274535,   /*!< speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_035_ACTIVE_E                            = 274536,   /*!< active speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_035_END_E                               = 278535,   /*!< speed limit end sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_035_END_ACTIVE_E                        = 278536,   /*!< active speed limit end sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_040_E                                     = 274540,   /*!< speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_040_ACTIVE_E                            = 274541,   /*!< active speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_040_END_E                               = 278540,   /*!< speed limit end sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_040_END_ACTIVE_E                        = 278541,   /*!< active speed limit end sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_045_E                                     = 274545,   /*!< speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_045_ACTIVE_E                            = 274546,   /*!< active speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_045_END_E                               = 278545,   /*!< speed limit end sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_045_END_ACTIVE_E                        = 278546,   /*!< active speed limit end sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_050_E                                     = 274550,   /*!< speed limit sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_050_ACTIVE_E                            = 274551,   /*!< active speed limit sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_050_END_E                               = 278550,   /*!< speed limit end sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_050_END_ACTIVE_E                        = 278551,   /*!< active speed limit end sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_055_E                                   = 274555,   /*!< speed limit sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_055_ACTIVE_E                            = 274556,   /*!< active speed limit sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_055_END_E                               = 278555,   /*!< speed limit end sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_055_END_ACTIVE_E                        = 278556,   /*!< active speed limit end sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_060_E                                   = 274560,   /*!< speed limit sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_060_ACTIVE_E                            = 274561,   /*!< active speed limit sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_060_END_E                               = 278560,   /*!< speed limit end sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_060_END_ACTIVE_E                        = 278561,   /*!< active speed limit end sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_065_E                                   = 274565,   /*!< speed limit sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_065_ACTIVE_E                            = 274566,   /*!< active speed limit sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_065_END_E                               = 278565,   /*!< speed limit end sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_065_END_ACTIVE_E                        = 278566,   /*!< active speed limit end sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_070_E                                   = 274570,   /*!< speed limit sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_070_ACTIVE_E                            = 274571,   /*!< active speed limit sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_070_END_E                               = 278570,   /*!< speed limit end sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_070_END_ACTIVE_E                        = 278571,   /*!< active speed limit end sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_075_E                                   = 274575,   /*!< speed limit sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_075_ACTIVE_E                            = 274576,   /*!< active speed limit sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_075_END_E                               = 278575,   /*!< speed limit end sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_075_END_ACTIVE_E                        = 278576,   /*!< active speed limit end sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_080_E                                   = 274580,   /*!< speed limit sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_080_ACTIVE_E                            = 274581,   /*!< active speed limit sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_080_END_E                               = 278580,   /*!< speed limit end sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_080_END_ACTIVE_E                        = 278581,   /*!< active speed limit end sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_085_E                                   = 274585,   /*!< speed limit sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_085_ACTIVE_E                            = 274586,   /*!< active speed limit sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_085_END_E                               = 278585,   /*!< speed limit end sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_085_END_ACTIVE_E                        = 278586,   /*!< active speed limit end sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_090_E                                   = 274590,   /*!< speed limit sign "90" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_090_ACTIVE_E                            = 274591,   /*!< active speed limit sign "90" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_090_END_E                               = 278590,   /*!< speed limit end sign "90" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_090_END_ACTIVE_E                        = 278591,   /*!< active speed limit end sign "90" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_095_E                                   = 274595,   /*!< speed limit sign "95" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_095_ACTIVE_E                            = 274596,   /*!< active speed limit sign "95" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_095_END_E                               = 278595,   /*!< speed limit end sign "95" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_095_END_ACTIVE_E                        = 278596,   /*!< active speed limit end sign "95" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_100_E                                   = 274600,   /*!< speed limit sign "100" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_100_ACTIVE_E                            = 274601,   /*!< active speed limit sign "100" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_100_END_E                               = 278600,   /*!< speed limit end sign "100" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_100_END_ACTIVE_E                        = 278601,   /*!< active speed limit end sign "100" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_110_E                                   = 274610,   /*!< speed limit sign "110" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_110_ACTIVE_E                            = 274611,   /*!< active speed limit sign "110" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_110_END_E                               = 278610,   /*!< speed limit end sign "110" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_110_END_ACTIVE_E                        = 278611,   /*!< active speed limit end sign "110" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_120_E                                   = 274620,   /*!< speed limit sign "120" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_120_ACTIVE_E                            = 274621,   /*!< active speed limit sign "120" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_120_END_E                               = 278620,   /*!< speed limit end sign "120" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_120_END_ACTIVE_E                        = 278621,   /*!< active speed limit end sign "120" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_130_E                                   = 274630,   /*!< speed limit sign "130" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_130_ACTIVE_E                            = 274631,   /*!< active speed limit sign "130" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_130_END_E                               = 278630,   /*!< speed limit end sign "130" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_130_END_ACTIVE_E                        = 278631,   /*!< active speed limit end sign "130" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_140_E                                  = 274640,   /*!< speed limit sign "140" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_140_ACTIVE_E                            = 274641,   /*!< active speed limit sign "140" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_140_END_E                               = 278640,   /*!< speed limit end sign "140" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_140_END_ACTIVE_E                        = 278641,   /*!< active speed limit end sign "140" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_150_E                                   = 274650,   /*!< speed limit sign "150" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_150_ACTIVE_E                            = 274651,   /*!< active speed limit sign "150" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_150_END_E                               = 278650,   /*!< speed limit end sign "150" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_150_END_ACTIVE_E                        = 278651,   /*!< active speed limit end sign "150" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_160_E                                   = 274660,   /*!< speed limit sign "160" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_160_ACTIVE_E                            = 274661,   /*!< active speed limit sign "160" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_160_END_E                               = 278660,   /*!< speed limit end sign "160" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_160_END_ACTIVE_E                        = 278661,   /*!< active speed limit end sign "160" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_170_E                                   = 274670,   /*!< speed limit sign "170" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_170_ACTIVE_E                            = 274671,   /*!< active speed limit sign "170" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_170_END_E                               = 278670,   /*!< speed limit end sign "170" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_170_END_ACTIVE_E                        = 278671,   /*!< active speed limit end sign "170" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_180_E                                   = 274680,   /*!< speed limit sign "180" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_180_ACTIVE_E                            = 274681,   /*!< active speed limit sign "180" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_180_END_E                               = 278680,   /*!< speed limit end sign "180" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_180_END_ACTIVE_E                        = 278681,   /*!< active speed limit end sign "180" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_190_E                                   = 274690,   /*!< speed limit sign "190" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_190_ACTIVE_E                            = 274691,   /*!< active speed limit sign "190" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_190_END_E                               = 278690,   /*!< speed limit end sign "190" */
    SR_TYPE_SIGN_CLASS_MAIN_SL_190_END_ACTIVE_E                        = 278691,   /*!< active speed limit end sign "190" */
    SR_TYPE_SIGN_CLASS_MAIN_ENVIRONMENTAL_ZONE_E                       = 270100,   /*!< environmental zone sign */
    SR_TYPE_SIGN_CLASS_MAIN_ENVIRONMENTAL_ZONE_END_E                   = 270200,   /*!< environmental zone end sign */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_E                                  = 274990,   /*!< garbage */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_ACTIVE_E                           = 274991,   /*!< active garbage */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_END_E                              = 278990,   /*!< end garbage */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_END_ACTIVE_E                       = 278991,   /*!< active end garbage */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_DIR_ARROW_E                        = 209990,   /*!< directional garbage */
    SR_TYPE_SIGN_CLASS_MAIN_CAR_NO_PASSING_E                           = 276000,   /*!< car no passing sign */
    SR_TYPE_SIGN_CLASS_MAIN_CAR_NO_PASSING_ACTIVE_E                    = 276001,   /*!< active car no passing sign */
    SR_TYPE_SIGN_CLASS_MAIN_CAR_NO_PASSING_END_E                       = 280000,   /*!< car no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_CAR_NO_PASSING_END_ACTIVE_E                = 280001,   /*!< active car no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_TRUCK_NO_PASSING_E                         = 277000,   /*!< truck no passing sign */
    SR_TYPE_SIGN_CLASS_MAIN_TRUCK_NO_PASSING_ACTIVE_E                  = 277001,   /*!< active truck no passing sign */
    SR_TYPE_SIGN_CLASS_MAIN_TRUCK_NO_PASSING_END_E                     = 281000,   /*!< truck no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_TRUCK_NO_PASSING_END_ACTIVE_E              = 281001,   /*!< active truck no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_NO_PASSING_END_E                    = 280100,   /*!< car/truck no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_NO_PASSING_END_ACTIVE_E             = 280101,   /*!< active car/truck no passing end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_TWO_DIGIT_END_E                     = 278200,   /*!< two digit speed limit end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_TWO_DIGIT_END_ACTIVE_E              = 278201,   /*!< active two digit speed limit end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_THREE_DIGIT_END_E                   = 278300,   /*!< three digit speed limit end sign */
    SR_TYPE_SIGN_CLASS_MAIN_BUNDLE_THREE_DIGIT_END_ACTIVE_E            = 278301,   /*!< active three digit speed limit end sign */
    SR_TYPE_SIGN_CLASS_MAIN_UNKNOWN_DIGIT_END_E                        = 278000,   /*!< speed limit end with unknown number of digits */
    SR_TYPE_SIGN_CLASS_MAIN_UNKNOWN_DIGIT_END_ACTIVE_E                 = 278001,   /*!< active speed limit end with unknown number of digits */
    SR_TYPE_SIGN_CLASS_MAIN_GENERAL_END_E                              = 282000,   /*!< general end sign */
    SR_TYPE_SIGN_CLASS_MAIN_GENERAL_END_ACTIVE_E                       = 282001,   /*!< active general end sign */
    SR_TYPE_SIGN_CLASS_MAIN_CITY_LIMIT_HOUSE_BEGIN_E                  = 290000,   /*!< begin of city limit, round sign with house (in Israel) */
    SR_TYPE_SIGN_CLASS_MAIN_CITY_LIMIT_HOUSE_END_E                     = 290100,   /*!< end of city limit, round sign with house (in Israel) */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_TURN_LEFT_E                     = 209100,   /*!< directional arrow left turn */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_TURN_RIGHT_E                     = 209200,   /*!< directional arrow right turn */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_STRAIGHT_E                        = 209300,   /*!< directional arrow straight ahead */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_SIDE_LEFT_E                     = 211100,   /*!< directional arrow to left side */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_SIDE_RIGHT_E                     = 211200,   /*!< directional arrow to right side */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_STRAIGHT_AND_TURN_LEFT_E        = 214100,   /*!< directional arrow straight ahead and left turn */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_STRAIGHT_AND_TURN_RIGHT_E       = 214200,   /*!< directional arrow straight ahead and right turn */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_PASS_LEFT_E                     = 222100,   /*!< directional arrow pass on left side */
    SR_TYPE_SIGN_CLASS_MAIN_DIR_ARROW_PASS_RIGHT_E                    = 222200,   /*!< directional arrow pass on right side */
    SR_TYPE_SIGN_CLASS_MAIN_ROUNDABOUT_E                                = 215000,   /*!< roundabout sign */
    SR_TYPE_SIGN_CLASS_MAIN_STOP_E                                      = 206000,   /*!< stop sign */
    SR_TYPE_SIGN_CLASS_MAIN_STOP_CONFUSED_E                             = 206000,   /*!< stop sign being confused by the super classifier */
    SR_TYPE_SIGN_CLASS_MAIN_NO_ENTRY_E                                  = 267000,   /*!< no entry sign */
    SR_TYPE_SIGN_CLASS_DANGER_CROSS_ROAD_SMALL_ROAD_E                   = 301000,   /*!< danger sign cross road small road */
    SR_TYPE_SIGN_CLASS_MAIN_CITY_LIMIT_BEGIN_E                        = 310000,   /*!< begin of city limit sign */
    SR_TYPE_SIGN_CLASS_MAIN_CITY_LIMIT_END_E                           = 311000,   /*!< end of city limit sign */
    SR_TYPE_SIGN_CLASS_MAIN_PLAY_STREET_BEGIN_E                       = 325000,   /*!< begin of play street area */
    SR_TYPE_SIGN_CLASS_MAIN_PLAY_STREET_END_E                          = 326000,   /*!< end of play street area */
    SR_TYPE_SIGN_CLASS_MAIN_HIGHWAY_BEGIN_E                           = 330000,   /*!< begin of highway */
    SR_TYPE_SIGN_CLASS_MAIN_HIGHWAY_END_E                              = 334000,   /*!< end of highway */
    SR_TYPE_SIGN_CLASS_MAIN_MOTORWAY_BEGIN_E                          = 331000,   /*!< begin of motorway */
    SR_TYPE_SIGN_CLASS_MAIN_MOTORWAY_END_E                             = 336000,   /*!< end of motorway */
    SR_TYPE_SIGN_CLASS_MAIN_COLCLS_GARBAGE_E                            = 339990,   /*!< color classifier garbage */
    //SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_LIMIT                           = 874000,   /*!< US speed limit cluster class */
    //SR_TYPE_SIGN_CLASS_MAIN_US_SPEED                                 = 874001,   /*!< US speed cluster class */
    //SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM                               = 874002,   /*!< US maximum cluster class */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_005_E                               = 874505,   /*!< US speed limit sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_005_E                            = 874506,   /*!< US speed sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_005_E                          = 874507,   /*!< US/CA maximum limit sign "5" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_010_E                                = 874510,   /*!< US speed limit sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_010_E                            = 874511,   /*!< US speed sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_010_E                          = 874512,   /*!< US/CA maximum limit sign "10" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_015_E                               = 874515,   /*!< US speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_015_E                            = 874516,   /*!< US speed sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_015_E                          = 874517,   /*!< US/CA maximum limit sign "15" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_020_E                               = 874520,   /*!< US speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_020_E                            = 874521,   /*!< US speed sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_020_E                          = 874522,   /*!< US/CA maximum limit sign "20" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_025_E                                = 874525,   /*!< US speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_025_E                             = 874526,   /*!< US speed sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_025_E                           = 874527,   /*!< US/CA maximum limit sign "25" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_030_E                                = 874530,   /*!< US speed limit sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_030_E                             = 874531,   /*!< US speed sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_030_E                           = 874532,   /*!< US/CA maximum limit sign "30" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_030_E                            = 874533,   /*!< US/CA led digit "30" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_035_E                                = 874535,   /*!< US speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_035_E                             = 874536,   /*!< US speed sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_035_E                           = 874537,   /*!< US/CA maximum limit sign "35" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_035_E                            = 874538,   /*!< US/CA led digit "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_040_E                                = 874540,   /*!< US speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_040_E                             = 874541,   /*!< US speed sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_040_E                           = 874542,   /*!< US/CA maximum limit sign "40" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_040_E                            = 874543,   /*!< US/CA led digit "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_045_E                                = 874545,   /*!< US speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_045_E                             = 874546,   /*!< US speed sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_045_E                           = 874547,   /*!< US/CA maximum limit sign "45" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_045_E                            = 874548,   /*!< US/CA led digit "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_050_E                                = 874550,   /*!< US speed limit sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_050_E                             = 874551,   /*!< US speed sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_050_E                           = 874552,   /*!< US/CA maximum limit sign "50" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_050_E                            = 874553,   /*!< US/CA led digit "50" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_055_E                                = 874555,   /*!< US speed limit sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_055_E                             = 874556,   /*!< US speed sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_055_E                           = 874557,   /*!< US/CA maximum limit sign "55" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_055_E                            = 874558,   /*!< US/CA led digit "55" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_060_E                                = 874560,   /*!< US speed limit sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_060_E                             = 874561,   /*!< US speed sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_060_E                           = 874562,   /*!< US/CA maximum limit sign "60" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_060_E                            = 874563,   /*!< US/CA led digit "60" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_065_E                                = 874565,   /*!< US speed limit sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_065_E                             = 874566,   /*!< US speed sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_065_E                          = 874567,   /*!< US/CA maximum limit sign "65" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_065_E                            = 874568,   /*!< US/CA led digit "65" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_070_E                                = 874570,   /*!< US speed limit sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_070_E                             = 874571,   /*!< US speed sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_070_E                           = 874572,   /*!< US/CA maximum limit sign "70" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_070_E                            = 874573,   /*!< US/CA led digit "70" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_075_E                                = 874575,   /*!< US speed limit sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_075_E                             = 874576,   /*!< US speed sign "75" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_075_E                           = 874577,   /*!< US/CA maximum limit sign "75" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_075_E                            = 874578,   /*!< US/CA led digit "75" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_080_E                                = 874580,   /*!< US speed limit sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_080_E                             = 874581,   /*!< US speed sign "80" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_080_E                           = 874582,   /*!< US/CA maximum limit sign "80" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_080_E                            = 874583,   /*!< US/CA led digit "80" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_085_E                                = 874585,   /*!< US speed limit sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SPEED_085_E                             = 874586,   /*!< US speed sign "85" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_085_E                           = 874587,   /*!< US/CA maximum limit sign "85" (km/h)*/
    SR_TYPE_SIGN_CLASS_MAIN_US_SL_INV_085_E                            = 874588,   /*!< US/CA led digit "85" */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_090_E                           = 874592,   /*!< US/CA maximum limit sign "90" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_095_E                           = 874597,   /*!< US/CA maximum limit sign "95" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_100_E                           = 874602,   /*!< US/CA maximum limit sign "100" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_105_E                           = 874607,   /*!< US/CA maximum limit sign "105" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_110_E                           = 874612,   /*!< US/CA maximum limit sign "110" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_115_E                           = 874617,   /*!< US/CA maximum limit sign "115" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_MAXIMUM_120_E                           = 874622,   /*!< US/CA maximum limit sign "120" (km/h) */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_005_E                            = 875505,   /*!< US truck speed limit sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_010_E                            = 875510,   /*!< US truck speed limit sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_015_E                            = 875515,   /*!< US truck speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_020_E                            = 875520,   /*!< US truck speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_025_E                             = 875525,   /*!< US truck speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_030_E                             = 875530,   /*!< US truck speed limit sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_035_E                             = 875535,   /*!< US truck speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_040_E                             = 875540,   /*!< US truck speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_045_E                             = 875545,   /*!< US truck speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_050_E                             = 875550,   /*!< US truck speed limit sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_055_E                             = 875555,   /*!< US truck speed limit sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_060_E                             = 875560,   /*!< US truck speed limit sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_US_TRUCK_065_E                             = 875565,   /*!< US truck speed limit sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_005_E                             = 876505,   /*!< US exit speed limit sign "5" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_010_E                             = 876510,   /*!< US exit speed limit sign "10" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_015_E                             = 876515,   /*!< US exit speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_020_E                             = 876520,   /*!< US exit speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_025_E                              = 876525,   /*!< US exit speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_030_E                              = 876530,   /*!< US exit speed limit sign "30" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_035_E                              = 876535,   /*!< US exit speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_040_E                              = 876540,   /*!< US exit speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_EXIT_045_E                              = 876545,   /*!< US exit speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_035_E                             = 877535,   /*!< US night speed limit sign "35" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_040_E                             = 877540,   /*!< US night speed limit sign "40" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_045_E                             = 877545,   /*!< US night speed limit sign "45" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_050_E                             = 877550,   /*!< US night speed limit sign "50" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_055_E                             = 877555,   /*!< US night speed limit sign "55" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_060_E                             = 877560,   /*!< US night speed limit sign "60" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_065_E                             = 877565,   /*!< US night speed limit sign "65" */
    SR_TYPE_SIGN_CLASS_MAIN_US_NIGHT_070_E                             = 877570,   /*!< US night speed limit sign "70" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SCHOOL_015_E                           = 878515,   /*!< US school speed limit sign "15" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SCHOOL_020_E                           = 878520,   /*!< US school speed limit sign "20" */
    SR_TYPE_SIGN_CLASS_MAIN_US_SCHOOL_025_E                            = 878525,   /*!< US school speed limit sign "25" */
    SR_TYPE_SIGN_CLASS_MAIN_US_GARBAGE_E                               = 879990,   /*!< US classifier garbage */
    SR_TYPE_SIGN_CLASS_MAIN_PROHIB_ALL_E                               = 250000,   /*!< prohib all */
    SR_TYPE_SIGN_CLASS_MAIN_PROHIB_CAR_E                               = 251000,   /*!< prohib car */
    SR_TYPE_SIGN_CLASS_MAIN_PROHIB_MOTORBIKE_CAR_E                     = 260000,   /*!< prohib motorbike car */
    SR_TYPE_SIGN_CLASS_MAIN_GARBAGE_PROHIB_E                           = 250990,   /*!< prohib garbage */
    SR_TYPE_SIGN_CLASS_MAIN_ENVIRONMENTAL_ZONE_GREEN_E                 = 270110,   /*!< prohib garbage */

    SR_TYPE_SIGN_CLASS_SUPPL_DISTANCE_RESTRICTION_E                    = 710000,   /*!< Custom one for XX-YYm */
    SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT_XYT_E                              = 105251,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT-(CZ,DE,FR, IT,PL, SK-countries)*/
    SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT_PLUS_XYT_E                         = 105252,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT-(BE-country)*/
    SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT_GT_E                               = 105253,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT-(LU-country)*/
    SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT_LS_E                               = 105254,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_WEIGHT-(LU-country)*/
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE_METERS_E                = 100440,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE-(AT, CZ,DE, ES, FR, IE, IT, LU, NL,PL, PT,SK, BG, SI-countries)*/
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE_KILOMETERS_E            = 100441,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE-(DK-country)*/
    SR_TYPE_SIGN_CLASS_SUPPL_VALID_FOR_DISTANCE_RANGE_METERS_E         = 100140,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE-(DK-country)*/
    SR_TYPE_SIGN_CLASS_SUPPL_TIME_RESTRICTION_XXH_E                    = 104031,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE-(CZ, DE, NL, HU, LV-countries)*/
    SR_TYPE_SIGN_CLASS_SUPPL_TIME_RESTRICTION_XXH_DK_E                 = 104032,   /*!< subclass of SR_TYPE_SIGN_CLASS_SUPPL_VALID_IN_DISTANCE-(DK-country)*/

    /* CoClf classes */
    SR_TYPE_COUNTRY_CLASS_ECE_AL_E                                     = 8,
    SR_TYPE_COUNTRY_CLASS_ECE_AT_E                                     = 40,
    SR_TYPE_COUNTRY_CLASS_ECE_BE_E                                     = 56,
    SR_TYPE_COUNTRY_CLASS_ECE_BG_E                                     = 100,
    SR_TYPE_COUNTRY_CLASS_ECE_CH_E                                     = 756,      /*!< includes CH, LI */
    SR_TYPE_COUNTRY_CLASS_ECE_CZ_E                                     = 203,
    SR_TYPE_COUNTRY_CLASS_ECE_DE_E                                     = 276,
    SR_TYPE_COUNTRY_CLASS_ECE_DK_E                                     = 208,
    SR_TYPE_COUNTRY_CLASS_ECE_EE_E                                     = 233,
    SR_TYPE_COUNTRY_CLASS_ECE_ES_E                                     = 724,      /*!< includes ES, GI, AD */
    SR_TYPE_COUNTRY_CLASS_ECE_FI_E                                     = 246,
    SR_TYPE_COUNTRY_CLASS_ECE_FR_E                                     = 250,      /*!< includes FR, MC */
    SR_TYPE_COUNTRY_CLASS_ECE_GB_E                                     = 826,
    SR_TYPE_COUNTRY_CLASS_ECE_GR_E                                     = 300,
    SR_TYPE_COUNTRY_CLASS_ECE_HU_E                                     = 348,
    SR_TYPE_COUNTRY_CLASS_ECE_IE_E                                     = 372,
    SR_TYPE_COUNTRY_CLASS_ECE_IT_E                                     = 380,      /*!< includes IT, SM, VA */
    SR_TYPE_COUNTRY_CLASS_ECE_LT_E                                     = 440,
    SR_TYPE_COUNTRY_CLASS_ECE_LU_E                                     = 442,
    SR_TYPE_COUNTRY_CLASS_ECE_LV_E                                     = 428,
    SR_TYPE_COUNTRY_CLASS_ECE_NL_E                                     = 528,
    SR_TYPE_COUNTRY_CLASS_ECE_NO_E                                     = 578,
    SR_TYPE_COUNTRY_CLASS_ECE_PL_E                                     = 616,
    SR_TYPE_COUNTRY_CLASS_ECE_PT_E                                     = 620,
    SR_TYPE_COUNTRY_CLASS_ECE_RU_E                                     = 643,
    SR_TYPE_COUNTRY_CLASS_ECE_SE_E                                     = 752,
    SR_TYPE_COUNTRY_CLASS_ECE_SI_E                                     = 705,
    SR_TYPE_COUNTRY_CLASS_ECE_SK_E                                     = 703,
    SR_TYPE_COUNTRY_CLASS_ECE_RO_E                                     = 642,
    SR_TYPE_COUNTRY_CLASS_ECE_TR_E                                     = 792,
    SR_TYPE_COUNTRY_CLASS_ECE_HR_E                                     = 191,
    SR_TYPE_COUNTRY_CLASS_ECE_CY_E                                     = 196,
    SR_TYPE_COUNTRY_CLASS_ECE_UA_E                                     = 804,
    SR_TYPE_COUNTRY_CLASS_ECE_IL_E                                     = 376
    //SR_TYPE_SIGN_CLASS_INT_MAX = INT_MAX
} ;

// }
}
